import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Layout from '../components/Layout/Layout'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Layout>
          <div>러ㅣㄴ머래ㅑ저래ㅓㄹㅁ재ㅑㄹ저ㅐㄹ</div>
        </Layout>
      </main>
    </div>
  )
}

export default Home
